services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install --no-root
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
