# This workflow will build a docker image and push it to GCP Artifact Registry.
#
# It will then deploy the application in Cloud Run.

name: Docker build and push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  IMAGE: title-belt-nhl
  IMAGE_TAG: latest

jobs:
  build:
    name: Docker build, push, deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 'Docker build'
      run: |-
        docker build \
          --tag "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_GAR_REPOSITORY }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}" .

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SECRET_KEY }}'
        token_format: 'access_token'

    - uses: 'docker/login-action@v3'
      name: 'Docker login'
      with:
        registry: '${{ vars.GCP_REGION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Docker push'
      run: |-
        docker push "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_GAR_REPOSITORY }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: title-belt-app
        region: ${{ vars.GCP_REGION }}
        image: "${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_GAR_REPOSITORY }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}"
    
    - name: 'URL output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
