# This workflow will build a docker image and push it to GCP Artifact Registry.
#
# It will then deploy the application in Cloud Run.

name: Docker build and push to Artifact Registry

on:
  push:
    branches:
      - main
      - setup-gcp

env:
  IMAGE: title-belt-nhl
  IMAGE_TAG: latest

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 'Docker build'
      run: |-
        docker build \
          --tag "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_GAR_REPOSITORY }}/$IMAGE:$IMAGE_TAG" .
  
  push:
    name: Docker push
    needs:
    - build
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SECRET_KEY }}'
        token_format: 'access_token'

    - uses: 'docker/login-action@v3'
      name: 'Docker login'
      with:
        registry: '${{ secrets.GCP_REGION }}-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: 'Docker push'
      run: |-
        docker push "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_GAR_REPOSITORY }}/$IMAGE:$IMAGE_TAG"

  deploy-image:
    name: Cloud Run deploy
    needs:
    - push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: title-belt-app
        region: ${{ secrets.GCP_REGION }}
        image: "${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_GAR_REPOSITORY }}/$IMAGE:$IMAGE_TAG"
    
    - name: 'URL output'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
